packages:
  - web
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - jsdom@30.0.0
overrides:
  esbuild: ^0.28.1
  "@codemirror/language": ^6.12.4
  "@codemirror/state": ^6.7.1
  "@codemirror/view": ^6.43.6
